#!/usr/bin/env bash
if [[ "${NB_UID}not-on-binder" -ne "not-on-binder" ]]; then
  if [[ "${CONDA_PREFIX}no-conda-prefix" = "no-conda-prefix" ]]; then
    export CONDA_PREFIX=$CONDA_DIR
  fi
fi

set -eux
python -m pip install -e ./packages/ipywxyz --ignore-installed --no-dependencies

jlpm bootstrap
jupyter labextension install $(cat labex.txt) --no-build
jupyter lab build
