#!/usr/bin/env bash
set -eux
python -m _scripts._setup

jupyter lab clean
jlpm cache clean
jlpm bootstrap
jupyter labextension install $(cat labex.txt) --no-build
jupyter labextension list
jupyter lab build --dev-build=False --minimize=True --debug
jupyter labextension list
