name: wxyz-atest

channels:
  - https://conda.anaconda.org/conda-forge

dependencies:
  - firefox =78
  - geckodriver
  - robotframework >=4
  - robotframework-lint
  - robotframework-pabot
  - robotframework-seleniumlibrary
