name: wxyz-atest

channels:
  - conda-forge
  - nodefaults

dependencies:
  - firefox =102
  - geckodriver
  - robotframework >=6
  - robotframework-tidy
  - robotframework-robocop
  - robotframework-pabot
  - robotframework-seleniumlibrary
