name: wxyz-base

channels:
  - conda-forge
  - nodefaults

dependencies:
  - bs4
  - doit
  - flit >=3.8
  - importnb
  - ipywidgets >=8,<9
  - jupyterlab >=3,<4
  - ipykernel !=6.19.*
  - pip
  - python
  - twine
