name: wxyz-base

channels:
  - https://conda.anaconda.org/conda-forge
  - nodefaults

dependencies:
  - bs4
  - doit
  - importnb
  - ipywidgets
  - jupyterlab
  - pip
  - python
  - twine
  # TODO: remove at some point
  - jedi <0.18.0
  - nbformat >=5,!=5.1.0,!=5.1.1
