name: wxyz-binder

channels:
  - https://conda.anaconda.org/conda-forge

dependencies:
  - jupyter-lsp-python-lsp-server
  - jupyter-starters
  - jupyterhub-singleuser
  - jupyterlab-lsp
  - jupyterlab-tour
  - nbgitpuller
  - nbresuse
