name: wxyz-binder

channels:
  - conda-forge
  - nodefaults

dependencies:
  - jupyter-lsp-python-plugins
  - jupyter-starters
  - jupyterhub-singleuser
  - jupyterlab-lsp
  - jupyterlab-tour
  - nbgitpuller
  - nbresuse
