name: wxyz-binder

channels:
  - conda-forge
  - nodefaults

dependencies:
  - ipydrawio
  - jupyter-starters
  - jupyterhub-singleuser
  - jupyterlab-deck
  - jupyterlab-myst
  - jupyterlab-tour
  - nbgitpuller
  - nbresuse
  - nodejs >=18,<19
