name: wxyz-docs

channels:
  - conda-forge
  - nodefaults

dependencies:
  - cairosvg
  - docutils >=0.19
  - doit
  - hunspell
  - hunspell-en
  - jupyterlab-webrtc-docprovider
  - myst-nb
  - nodejs >=16,!=17.*,<19
  - pkginfo
  - pydata-sphinx-theme
  - pytest-check-links >=0.4.4,!=4.3.3
  - python-build
  - python-graphviz
  - python-libarchive-c
  - recommonmark
  - sphinx-autobuild
  - sphinx-autodoc-typehints
  - sphinx-copybutton
  - sphinx-sitemap
  - tabulate
