name: wxyz-docs

channels:
  - conda-forge
  - nodefaults

dependencies:
  - cairosvg
  - hunspell
  - hunspell-en
  - myst-nb
  - nodejs >=16,!=17.*,<19
  - pydata-sphinx-theme
  - pytest-check-links >=0.4.4,!=4.3.3
  - python-graphviz
  - requests-cache
  - sphinx-autobuild
  - sphinx-autodoc-typehints
  - sphinx-copybutton
  - sphinx-sitemap
  - tabulate
