name: wxyz-tpot

channels:
  - https://conda.anaconda.org/conda-forge

dependencies:
  - cycler
  - dask
  - dask-labextension
  - dask-ml
  - distributed
  - ipympl
  - lime
  - matplotlib-base
  - scikit-image
  - scikit-learn
  - scikit-mdr
  - skrebate
  - tpot
  - umap-learn
  - yellowbrick
  # not actually used in demos/tests, yet...
  - bqplot
  - datashader
  - hvplot
  - ipycytoscape
  - ipylab
  - jupyterlab-classic
