name: wxyz-tpot

channels:
  - conda-forge
  - nodefaults

dependencies:
  - cycler
  - dask
  - dask-labextension
  - dask-ml
  - distributed
  - ipympl
  - lime
  - matplotlib-base
  - scikit-image
  - scikit-learn
  - scikit-mdr
  - skrebate
  - tpot
  - umap-learn
  - yellowbrick
